### ISSUE TITLE
Force function not run with MySQL on register

### ISSUE THREAD

**Issue by DaPigGuy** [DaPigGuy/PiggyAuth#58]
# DO NOT REMOVE THIS
Please make sure your issue complies with these guidelines:
- * [x] Be using PMMP
- * [x] Make sure the issue hasn't already been reported
- * [x] Make sure you are on the latest version of PMMP & PiggyAuth
- * [x] Have a detailed title like "Players are being kicked randomly"
- * [x] Provide any crash dumps or errors

#### **General**

Sometimes the force function is not run after registering, resulting in effects not being removed, bossbars not removed, or gamemode set. This issue only happens occasionally and started happening when async was added.

#### **Server Software:**
 PMMP

#### **Version of PiggyAuth:**
 3.0.0.17

#### **Data Provider:**

- [x] MySQL
- [ ] SQLite

#### **Steps to Reproduce the Issue**

1. Turn on MySQL
2. Register non stop until it happens

**Comment by miguel456** [comment]
Please please please please... Add more comments so I can better understand your codebase...  (Pardon me, only have been developing PHP for the past 2 years lol) My classes basically have a huge essay in a multi-line comment explaining what they do (although the code explains itself). Sometimes I also add small comments in certain lines (such as ternary statements) for code that doesn't explain itself right away.

If you did the same (not encouraging you to litter the code with comments xD),Me and other people could better understand the codebase so that we could better help you fix this bug.

**Comment by Thunder33345** [comment]
@miguel456 the functions SHOULD be self documented by names and calling from
it's somewhat messy honestly doe

**Comment by DaPigGuy** [comment]
When a player's password is reset using resetpassword, the sessions aren't created after for MySQL.

**Comment by DaPigGuy** [comment]
Fixed 2nd issue.

**Comment by DaPigGuy** [comment]
Commit 661e3739756f72d81568b4da58a6fd7ef1728636 seems to have fixed it.
